# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"H\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0f\x66irst_name_from\x18\x02 \x01(\t\x12\x16\n\x0elast_name_from\x18\x03 \x01(\t\"E\n\x12SendMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nlogin_from\x18\x02 \x01(\t\x12\r\n\x05id_to\x18\x03 \x01(\x05\"&\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x11GetMessageRequest\x12\r\n\x05login\x18\x01 \x01(\t\"0\n\x12GetMessageResponse\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message2\x81\x01\n\x0eMessageService\x12\x38\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\x12\x35\n\nGetMessage\x12\x12.GetMessageRequest\x1a\x13.GetMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=17
  _globals['_MESSAGE']._serialized_end=89
  _globals['_SENDMESSAGEREQUEST']._serialized_start=91
  _globals['_SENDMESSAGEREQUEST']._serialized_end=160
  _globals['_SENDMESSAGERESPONSE']._serialized_start=162
  _globals['_SENDMESSAGERESPONSE']._serialized_end=200
  _globals['_GETMESSAGEREQUEST']._serialized_start=202
  _globals['_GETMESSAGEREQUEST']._serialized_end=236
  _globals['_GETMESSAGERESPONSE']._serialized_start=238
  _globals['_GETMESSAGERESPONSE']._serialized_end=286
  _globals['_MESSAGESERVICE']._serialized_start=289
  _globals['_MESSAGESERVICE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
