version: "3"

services:
  auth:
    build: backend/auth_service/
    container_name: auth
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./backend:/auth/backend/
      - .env:/auth/.env
#    networks:
#      - service-network

  send_email:
    build: backend/send_email_service/
    container_name: send_email
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - ./backend:/send_email/backend/
      - .env:/send_email/.env
#    networks:
#      - service-network

  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
#    networks:
#      - service-network

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - frontend
#    networks:
#      - service-network

networks:
  service-network:
    driver: bridge