version: "3"

services:
  api:
    build: backend/api/
    container_name: api
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./backend/common:/api/backend/common
      - .env:/api/.env

  auth:
    build: backend/auth_service/
    container_name: auth
    ports:
      - "9003:9003"
    restart: always
    volumes:
      - ./backend/common:/auth/backend/common
      - .env:/auth/.env

  common_information:
    build: backend/common_information_service/
    container_name: common_information
    ports:
      - "9002:9002"
    restart: always
    volumes:
      - ./backend/common:/common_information/backend/common
      - .env:/common_information/.env

  send_email:
    build: backend/send_email_service/
    container_name: send_email
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - ./backend/common:/send_email/backend/common
      - .env:/send_email/.env

  orders:
    build: backend/orders_service/
    container_name: orders
    ports:
      - "9004:9004"
    restart: always
    volumes:
      - ./backend/common:/orders/backend/common
      - .env:/orders/.env

  message:
    build: backend/message_service/
    container_name: message
    ports:
      - "9005:9005"
    volumes:
      - ./backend/common:/message/backend/common
      - .env:/message/.env

  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - frontend